/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnapp;

import java.io.File;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import joltconnlib.LocalStorage;
import joltconnlib.Configuration;
import joltconnlib.JoltStorage;
import joltconnlib.javaSync.JavaNetSync;

public class AppJava {

    public static void main(String[] args) {
        try {
            MessageDigest sha = MessageDigest.getInstance("SHA-1");
            JavaNetSync javaSync = new JavaNetSync(sha);
            LocalStorage localStorage = new LocalStorage(new Configuration("./gameConfig.json", "gameA"), javaSync);
            localStorage.writeMetaFilesToDisk();
            JoltStorage joltStorage = new JoltStorage(new Configuration("./gameConfig.json", "gameB"), javaSync);
            joltStorage.writeMetaFilesToDisk();
            joltStorage.writeFilesToDisk();
        } catch (NoSuchAlgorithmException e) {
            System.out.print("No sha-1 on this machine");
        }
    }
}
