/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnapp;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import joltconnlib.Storage;
import joltconnlib.configuration.Configuration;
import joltconnlib.javaSync.JavaLocalSync;
import joltconnlib.javaSync.JavaNetSync;

public class AppJava {

    public static void main(String[] args) {
        try {
            MessageDigest sha = MessageDigest.getInstance("SHA-1");
            JavaNetSync javaSync = new JavaNetSync(sha);
            JavaLocalSync localSync = new JavaLocalSync(sha);
            Storage storage = new Storage(new Configuration("../app/gameConfig.json", "gameA"), javaSync, localSync);
            storage.storeFilesLocally();
        } catch (NoSuchAlgorithmException e) {
            System.out.print("No sha-1 on this machine");
        }
    }
}
