/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnapp;

import java.io.File;

import joltconnlib.LocalStorage;
import joltconnlib.Configuration;
import joltconnlib.JoltStorage;

public class App {

    public static void main(String[] args) {

        Configuration config = new Configuration(new File("./gameConfig.json"), "gameA");
        LocalStorage fs = new LocalStorage(config);

        
        // FolderState fs = new FolderState();

        // DataStoreState dss = new DataStoreState();
        // DataStoreState.setGameStateFromFile(new File("gameConfig.json"), "gameA");
        // dss.parseDirectory();
        
        // System.out.println(fs.parseDirectory(new File("..")));
    }
}
