/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnapp;

import java.io.File;

import joltconnlib.FolderState;

public class App {

    public static void main(String[] args) {
        FolderState s = new FolderState();
        System.out.println(s.parseDirectory(new File("..")));
    }
}
