/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnapp;

import java.io.File;

import joltconnlib.LocalStorage;
import joltconnlib.Configuration;
import joltconnlib.JoltStorage;

public class App {

    public static void main(String[] args) {

        LocalStorage localStorage = new LocalStorage(new Configuration(new File("./gameConfig.json"), "gameA"));
        localStorage.writeMetaFilesToDisk();
        JoltStorage joltStorage = new JoltStorage(new Configuration(new File("./gameConfig.json"), "gameB"));
        joltStorage.writeMetaFilesToDisk();
        
        // FolderState fs = new FolderState();

        // DataStoreState dss = new DataStoreState();
        // DataStoreState.setGameStateFromFile(new File("gameConfig.json"), "gameA");
        // dss.parseDirectory();
        
        // System.out.println(fs.parseDirectory(new File("..")));
    }
}
