/*
 * This source file was generated by the Gradle 'init' task
 */
package joltconnlib;

import com.github.raeleus.gamejoltapi.GameJoltApi;

public class Lib {
    public String getGreeting() {
        return "Hello Lib!";
    }
}
